### ISSUE TITLE
🚀 Feature: Find/Create an Algorithm for book recommendation

### ISSUE THREAD

**Issue by hbdermott** [cs130-w21/book.ar#12]
As a user/reader, I would like the book recommendations to be more personally tuned to me, so that my reading experience can be more enjoyable and I can find books that I will like.

### Use Case

The initial recommendation system will be rather primitive, so this feature will be used to improve upon it so that a reader can more likely by recommended a book that they will like.

### Proposed Solution

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
Closing because of #19
