### ISSUE TITLE
🚀 Feature: integrate camera to react native

### ISSUE THREAD

**Issue by BryanPan342** [cs130-w21/book.ar#16]
As a user, I would like to take a picture of books so that I can upload it easily to the app.

### Proposed Solution

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by DonLe27** [comment]
This issue and the submit photo one are both probably going to use the react native image picker. There's a PR that adds the library if it would help to start with that.

**Comment by BryanPan342** [comment]
@DonLe27 is this closed?

**Comment by BryanPan342** [comment]
Closed
